# docker-compose.yml (place in root directory)
version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/professor_examples:/app/professor_examples
      - ./backend/temp_uploads:/app/temp_uploads
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}